# Generated by Django 5.2.7 on 2025-11-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_review_name_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
